/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hackeo;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nadina Mazzoni
 */
public class Hackeo extends javax.swing.JFrame {

    /**
     * Creates new form HAckeo
     */
    public Hackeo() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hackeos = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_todos = new javax.swing.JList<>();
        progress_bar = new javax.swing.JProgressBar();
        crear_hackeo_regular = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        codigo_crear_hack = new javax.swing.JTextField();
        nivel_riesgo = new javax.swing.JSpinner();
        crear_hackeo_super = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        codigo_crear_hack1 = new javax.swing.JTextField();
        nivel_riesgo1 = new javax.swing.JSpinner();
        simulador = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        cantidad_caracteres = new javax.swing.JSpinner();
        modificaregular = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        codigo_modificar_regular = new javax.swing.JTextField();
        nivel_modificar_regular = new javax.swing.JSpinner();
        modificarsuper = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        codigo_super_hackeo = new javax.swing.JTextField();
        nivel_modificar_super = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jButton1.setText("Crear hackeo regular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Simulacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Crear super hackeo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        lista_todos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(lista_todos);

        progress_bar.setString("Hackeando...");
        progress_bar.setStringPainted(true);

        javax.swing.GroupLayout hackeosLayout = new javax.swing.GroupLayout(hackeos.getContentPane());
        hackeos.getContentPane().setLayout(hackeosLayout);
        hackeosLayout.setHorizontalGroup(
            hackeosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hackeosLayout.createSequentialGroup()
                .addGroup(hackeosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hackeosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(hackeosLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hackeosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        hackeosLayout.setVerticalGroup(
            hackeosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hackeosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(hackeosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Crear hackeo");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nivel de riesgo:");

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        nivel_riesgo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout crear_hackeo_regularLayout = new javax.swing.GroupLayout(crear_hackeo_regular.getContentPane());
        crear_hackeo_regular.getContentPane().setLayout(crear_hackeo_regularLayout);
        crear_hackeo_regularLayout.setHorizontalGroup(
            crear_hackeo_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_hackeo_regularLayout.createSequentialGroup()
                .addGroup(crear_hackeo_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_hackeo_regularLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton5))
                    .addGroup(crear_hackeo_regularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nivel_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(crear_hackeo_regularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(crear_hackeo_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo_crear_hack, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        crear_hackeo_regularLayout.setVerticalGroup(
            crear_hackeo_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_hackeo_regularLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(crear_hackeo_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigo_crear_hack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crear_hackeo_regularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nivel_riesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(20, 20, 20))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Crear hackeo");

        jLabel5.setText("Codigo:");

        jLabel6.setText("Nivel de riesgo:");

        jButton6.setText("Crear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        nivel_riesgo1.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        javax.swing.GroupLayout crear_hackeo_superLayout = new javax.swing.GroupLayout(crear_hackeo_super.getContentPane());
        crear_hackeo_super.getContentPane().setLayout(crear_hackeo_superLayout);
        crear_hackeo_superLayout.setHorizontalGroup(
            crear_hackeo_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_hackeo_superLayout.createSequentialGroup()
                .addGroup(crear_hackeo_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_hackeo_superLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton6))
                    .addGroup(crear_hackeo_superLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nivel_riesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(crear_hackeo_superLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(crear_hackeo_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo_crear_hack1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        crear_hackeo_superLayout.setVerticalGroup(
            crear_hackeo_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_hackeo_superLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(crear_hackeo_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codigo_crear_hack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crear_hackeo_superLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nivel_riesgo1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(20, 20, 20))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Simulador");

        jLabel8.setText("Cantidad de caracteres: ");

        jButton8.setText("Simulador");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        cantidad_caracteres.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout simuladorLayout = new javax.swing.GroupLayout(simulador.getContentPane());
        simulador.getContentPane().setLayout(simuladorLayout);
        simuladorLayout.setHorizontalGroup(
            simuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simuladorLayout.createSequentialGroup()
                .addGroup(simuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simuladorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(simuladorLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel7))
                    .addGroup(simuladorLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton8)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        simuladorLayout.setVerticalGroup(
            simuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simuladorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addGroup(simuladorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cantidad_caracteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(40, 40, 40))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Modificar hackeo regular");

        jLabel10.setText("Codigo:");

        jLabel11.setText("Nivel de riesgo:");

        jButton9.setText("Modificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        nivel_modificar_regular.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout modificaregularLayout = new javax.swing.GroupLayout(modificaregular.getContentPane());
        modificaregular.getContentPane().setLayout(modificaregularLayout);
        modificaregularLayout.setHorizontalGroup(
            modificaregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificaregularLayout.createSequentialGroup()
                .addGroup(modificaregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificaregularLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton9))
                    .addGroup(modificaregularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nivel_modificar_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificaregularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(codigo_modificar_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificaregularLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(20, 20, 20))
        );
        modificaregularLayout.setVerticalGroup(
            modificaregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificaregularLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(modificaregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(codigo_modificar_regular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificaregularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nivel_modificar_regular, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(20, 20, 20))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Modificar super hackeo");

        jLabel13.setText("Codigo:");

        jLabel14.setText("Nivel de riesgo:");

        jButton10.setText("Modificar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        nivel_modificar_super.setModel(new javax.swing.SpinnerNumberModel(5, 5, 10, 1));

        javax.swing.GroupLayout modificarsuperLayout = new javax.swing.GroupLayout(modificarsuper.getContentPane());
        modificarsuper.getContentPane().setLayout(modificarsuperLayout);
        modificarsuperLayout.setHorizontalGroup(
            modificarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarsuperLayout.createSequentialGroup()
                .addGroup(modificarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarsuperLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton10))
                    .addGroup(modificarsuperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nivel_modificar_super, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarsuperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(codigo_super_hackeo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarsuperLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        modificarsuperLayout.setVerticalGroup(
            modificarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarsuperLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addGroup(modificarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(codigo_super_hackeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modificarsuperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nivel_modificar_super, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Todos los hackeos");

        jMenuItem1.setText("Ver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Refrescar() throws FileNotFoundException
    {
        ah.cargarArchivo();
        DefaultListModel modelo=(DefaultListModel)lista_todos.getModel();
        modelo.clear();
        for (int i = 0; i <ah.getHackeos().size(); i++) {
               modelo.addElement(ah.getHackeos().get(i));
               lista_todos.setModel(modelo);
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String codigo;
        int nivel;
        codigo=codigo_crear_hack.getText();
        nivel=Integer.parseInt(nivel_riesgo.getValue().toString());
        lista.add(new HackeoRegular(codigo,nivel));
        try {
            ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ah.getHackeos().add(new HackeoRegular(codigo,nivel));
        try {
            ah.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Hackeo regular creado exitosamente");
        try {
            Refrescar();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        crear_hackeo_regular.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        crear_hackeo_regular.setModal(true);
        crear_hackeo_regular.pack();
        crear_hackeo_regular.setLocationRelativeTo(this);
        crear_hackeo_regular.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String codigo;
        int nivel;
        codigo=codigo_crear_hack1.getText();
        nivel=Integer.parseInt(nivel_riesgo1.getValue().toString());
        lista.add(new HackeoSuper(codigo,nivel));
        try {
            ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ah.getHackeos().add(new HackeoSuper(codigo,nivel));
        JOptionPane.showMessageDialog(this, "Hackeo super creado exitosamente");
        try {
            Refrescar();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        crear_hackeo_super.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        crear_hackeo_super.setModal(true);
        crear_hackeo_super.pack();
        crear_hackeo_super.setLocationRelativeTo(this);
        crear_hackeo_super.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        hackeos.setModal(true);
        hackeos.pack();
        hackeos.setLocationRelativeTo(this);
        hackeos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try { 
            // TODO add your handling code here:
            ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ah.getHackeos().remove(lista_todos.getSelectedIndex());
        try {
            ah.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Refrescar();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        simulador.setModal(true);
        simulador.pack();
        simulador.setLocationRelativeTo(this);
        simulador.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

      int n=lista_todos.getSelectedIndex();
      int cant_car=Integer.parseInt(cantidad_caracteres.getValue().toString());
      DefaultListModel modelo=(DefaultListModel)lista_todos.getModel();
      simulador.dispose();
      cantidad_caracteres.setValue(0);
      Hacks user=lista.get(n);
      int cont=0;
      if(lista.get(n) instanceof HackeoRegular)
      {
              r=1+t.nextInt(5);
              if(((HackeoRegular)user).getExitosos()==0)
              {
                  cont=0;
              }
      }
      if(lista.get(n) instanceof HackeoSuper)
      {
          r=6+t.nextInt(10);
          if(((HackeoSuper)user).getFallidos()==0)
              {
                  cont=0;
              }
      }
      if(cont==0)
      {
          int niv=user.getNivel();
      int dur=0;
      if(user instanceof HackeoRegular)
      {
          dur=2;
      }
      else
      {
          dur=1;
      }
      progress_bar.setValue(0);
      progress_bar.setMaximum(dur*cant_car);
      adminProgress ab=new adminProgress(progress_bar, dur, cant_car);
      ab.start();
      if(r==niv && user instanceof HackeoRegular)
      {
          ab.setAvanzar(false);
          JOptionPane.showMessageDialog(this, "La simulacion se ha cancelado");
          ((HackeoRegular)user).Aumentar();
      }
      if(r==niv && user instanceof HackeoSuper)
      {
          ab.setAvanzar(false);
          JOptionPane.showMessageDialog(this, "La simulacion se ha cancelado");
          ((HackeoSuper)user).Aumentar();
      }
      }
      else if (cont>1)
      {
          JOptionPane.showMessageDialog(this, "Este hackeo ya ha lo ha probado antes");
      }
      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo=(DefaultListModel)lista_todos.getModel();
        JFileChooser fileChooser =new JFileChooser("./");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int seleccion=fileChooser.showOpenDialog(this);
        if (seleccion==JFileChooser.APPROVE_OPTION)
        {
            try {
                ah.cargarArchivo();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (int i = 0; i < ah.getHackeos().size(); i++) {
                modelo.addElement(ah.getHackeos().get(i));  
            }
            lista_todos.setModel(modelo);
            hackeos.setModal(true);
            hackeos.pack();
            hackeos.setLocationRelativeTo(this);
            hackeos.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.out.println("entra");
        try {
            ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        if(ah.getHackeos().get(lista_todos.getSelectedIndex()).getNivel()<=5)
        {
            System.out.println("entra1");
            codigo_modificar_regular.setText(ah.getHackeos().get(lista_todos.getSelectedIndex()).getCodigo());
            nivel_modificar_regular.setValue((ah.getHackeos().get(lista_todos.getSelectedIndex()).getNivel()));
            modificaregular.setModal(true);
           modificaregular.pack();
           modificaregular.setLocationRelativeTo(this);
           modificaregular.setVisible(true);
        }
        if(ah.getHackeos().get(lista_todos.getSelectedIndex()).getNivel() >5)
        {
           System.out.println("entra");
           codigo_super_hackeo.setText(ah.getHackeos().get(lista_todos.getSelectedIndex()).getCodigo());
           nivel_modificar_super.setValue((ah.getHackeos().get(lista_todos.getSelectedIndex()).getNivel()));
           modificarsuper.setModal(true);
           modificarsuper.pack();
           modificarsuper.setLocationRelativeTo(this);
           modificarsuper.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ah.getHackeos().get(lista_todos.getSelectedIndex()).setCodigo(codigo_modificar_regular.getText());
        ah.getHackeos().get(lista_todos.getSelectedIndex()).setNivel(Integer.parseInt(nivel_modificar_regular.toString()));
        try {
            ah.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        modificarsuper.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            // TODO add your handling code here:
            ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ah.getHackeos().get(lista_todos.getSelectedIndex()).setCodigo(codigo_super_hackeo.getText());
        ah.getHackeos().get(lista_todos.getSelectedIndex()).setNivel(Integer.parseInt(nivel_modificar_super.toString()));
        try {
            ah.escribirArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        modificaregular.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
        ah.cargarArchivo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hackeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(ah.getHackeos().size()==0)
        {
            JOptionPane.showMessageDialog(this, "No hay hackeos que guardar");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Se ha guardado el archivo extisamente");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hackeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hackeo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cantidad_caracteres;
    private javax.swing.JTextField codigo_crear_hack;
    private javax.swing.JTextField codigo_crear_hack1;
    private javax.swing.JTextField codigo_modificar_regular;
    private javax.swing.JTextField codigo_super_hackeo;
    private javax.swing.JDialog crear_hackeo_regular;
    private javax.swing.JDialog crear_hackeo_super;
    private javax.swing.JDialog hackeos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista_todos;
    private javax.swing.JDialog modificaregular;
    private javax.swing.JDialog modificarsuper;
    private javax.swing.JSpinner nivel_modificar_regular;
    private javax.swing.JSpinner nivel_modificar_super;
    private javax.swing.JSpinner nivel_riesgo;
    private javax.swing.JSpinner nivel_riesgo1;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JDialog simulador;
    // End of variables declaration//GEN-END:variables
ArrayList<Hacks>lista=new ArrayList();
Random t=new Random();
int r=0;
adminHacks ah=new adminHacks("./Hackeos.txt");
int cc=0;



}
